import re
from collections import UserDict, abc
from io import StringIO, TextIOBase
from pathlib import Path
from typing import Any

import ruamel.yaml as raml
from epicstuff import JDict, NewDict, open, run_fix_import  # noqa: A004, F401

from .schema import _format_data, _format_schema
from .stuff import beartype


file_like = str | Path | TextIOBase

class Dict[K, V](NewDict[K, V]):
	def _is_key_protected(self, key: str) -> bool:
		return key.startswith('_yaml_')

# basically, make ramuel use isinstance instead of type is
_rep = raml.RoundTripRepresenter.yaml_multi_representers.copy()
for _type in (raml.CommentedMap, dict):
	_rep[_type] = raml.RoundTripRepresenter.yaml_representers[_type]


class TAML(raml.YAML):
	def __init__(self, typ: list[str] | str | None = None, pure: Any = False, output: Any = None, plug_ins: Any = None) -> None:
		'''Just calls ruamel.yaml's init and changes a few default setting.'''
		super().__init__(typ=typ, pure=pure, output=output, plug_ins=plug_ins)
		self.representer.yaml_multi_representers = _rep

		self.indent(mapping=1, sequence=1, offset=1)
		self.width: int = 160  # pyright: ignore[reportIncompatibleVariableOverride]
	@beartype
	def load(self, stream: file_like, *schemas: abc.Mapping | file_like | Any) -> Any:
		'''Load file.

		Args:
			stream: Can be either path to file or text/string io
			*schemas: One or more schemas to apply to stream, can be either resolved dict, path to file, or text/string io

		Returns:
			A Dict from a ruamel.yaml CommentedMap

		'''
		self.check()

		if isinstance(stream, (str, Path)):
			with open(stream, 'r') as f:
				file = f.read()
		else:  # note, this else relies on beartype enforcing typing
			file = stream.read()

		# check for mixed indentation
		if re.search(r'^(?=[ \t]*\t)(?=[ \t]* )[ \t]+\S', file, flags=re.MULTILINE):
			print('warning: you have mixed indentation')
		# replace tabs after newline with 1 spaces for each tab, generated by claude
		file = re.sub(r'^(\t+)', lambda m: ' ' * len(m.group(1)), file, flags=re.MULTILINE)

		out = super().load(StringIO(''.join(file)))
		if isinstance(out, raml.CommentedMap):
			out = Dict(out)
		# todo: maybe convert dicts inside lists to Dict

		# for each schema, format/check with it
		for schema in schemas:
			# if the schema is path to file or file, process it
			if isinstance(schema, file_like):
				schema = _format_schema(taml.load(schema))
			out = _format_data(out, schema)
		return out
	@beartype
	def loads(self, stream: str, *schemas: abc.Mapping | file_like | Any, is_schema: bool = False) -> Any:
		'''Load string.

		Args:
			stream: yaml to load, as a string
			*schemas: One or more schemas to apply to stream, can be either resolved dict, path to file, or text/string io
			is_schema: are you loading a schema and it should be resolved

		Returns:
			A Dict from a ruamel.yaml CommentedMap

		'''
		out = self.load(StringIO(stream), *schemas)
		if is_schema:
			out = _format_schema(out)
		return out
	@beartype
	def dump(self, data: Any, stream: file_like, transform: abc.Callable | None = None) -> None:
		'''Convert data to yaml and save to file like object.

		Args:
			data: whatever ruamel.yaml accepts
			stream: Can be either path to file or text/string io
			transform: not super sure to be honest, just gets passed on to ruamel.yaml

		'''
		out = self.dumps(data, transform)

		# dump to stream
		if isinstance(stream, (str, Path)):
			with open(stream, 'w') as f:
				f.write(out)
		else:  # else is TextIO, enforced by beartype
			stream.write(out)
	def dumps(self, data: Any, transform: abc.Callable | None = None) -> str:
		'''Convert data to yaml and return as string.

		Args:
			data: whatever ruamel.yaml accepts
			transform: not super sure to be honest, just gets passed on to ruamel.yaml

		'''
		# create temporary "text file"
		tmp = StringIO()

		# dump to tmp
		self.check()
		if isinstance(data, JDict):
			data = data._t  # dump underlying dict
		if isinstance(data, UserDict):
			data = data.data  # dump underlying dict
		super().dump(data, tmp, transform=transform)
		tmp.seek(0)

		# convert indentation to tabs and return as string, generated by claude
		return re.sub(r'^ +', lambda m: '\t' * len(m.group(0)), tmp.read(), flags=re.MULTILINE)

	def check(self) -> None:
		if self.map_indent != 1 or self.sequence_indent != 1 or self.sequence_dash_offset != 1:
			print('warning: changing indentation may cause this to not work')


taml = TAML()
