import re
from collections import UserDict, abc
from io import StringIO, TextIOWrapper
from pathlib import Path
from typing import Any

from epicstuff import JDict, open, run_fix_import; Dict = JDict  # noqa: A004
from beartype import beartype, BeartypeConf
import ruamel.yaml as raml
from taml.schema import _format_schema, _format_data

beartype = beartype(conf=BeartypeConf(is_color=False))


class TAML(raml.YAML):
	def __init__(self: Any, *, typ: list[str] | str | None = None, pure: Any = False, output: Any = None, plug_ins: Any = None) -> None:
		'''Just calls ruamel.yaml's init and changes a few default setting.'''
		super().__init__(typ=typ, pure=pure, output=output, plug_ins=plug_ins)

		self.indent(mapping=1, sequence=1, offset=1)
		self.default_flow_style = None
		self.width = 160
	@beartype
	def load(self, stream: str | Path | TextIOWrapper | StringIO, *schemas: abc.Mapping | str | Path | TextIOWrapper | StringIO) -> Dict[str, Any]:
		'''Load file.

		Args:
			stream: Can be either path to file or text/string io
			*schemas: One or more schemas to apply to stream, can be either resolved dict, path to file, or text/string io

		Returns:
			A NewDict from a ruamel.yaml CommentedMap

		'''
		if isinstance(stream, (str, Path)):
			with open(stream, 'r') as f:
				file = f.read()
		else:  # note, this else relies on beartype enforcing typing
			file = stream.read()

		# replace tabs after newline with 1 spaces for each tab, generated by claude
		file = re.sub(r'^(\t+)', lambda m: ' ' * len(m.group(1)), file, flags=re.MULTILINE)

		out = Dict(super().load(StringIO(''.join(file))))

		# for each schema, format/check out with it
		for schema in schemas:
			# if the schema is not python object (load from file), format it
			if not isinstance(schema, abc.Mapping):
				schema = _format_schema(taml.load(schema))
			out = _format_data(out, schema)
		return out
	@beartype
	def loads(self, stream: str, *schemas: abc.Mapping | str | Path | TextIOWrapper, is_schema: bool = False) -> Dict[str, Any]:
		'''Load string.

		Args:
			stream: yaml to load, as a string
			*schemas: One or more schemas to apply to stream, can be either resolved dict, path to file, or text/string io
			is_schema: are you loading a schema and it should be resolved

		Returns:
			A Dict from a ruamel.yaml CommentedMap

		'''
		out = self.load(StringIO(stream), *schemas)
		if is_schema:
			_format_schema(out)
		return out
	def dump(self, data: Any, stream: Any = str | Path | TextIOWrapper | StringIO, transform: abc.Callable | None = None) -> None:
		'''Convert data to yaml and save to file like object.
		
		Args:
			data: whatever ruamel.yaml accepts
			stream: Can be either path to file or text/string io
			transform: not super sure to be honest, just gets passed on to ruamel.yaml
		
		'''
		out = self.dumps(data, transform)
		
		# dump to stream
		if isinstance(stream, (str, Path)):
			with open(stream, 'w') as f:
				f.write(out)
		elif isinstance(stream, (TextIOWrapper, StringIO)):
			stream.write(out)
		else:
			raise TypeError
	def dumps(self, data: Any, transform: abc.Callable | None = None) -> str:
		'''Convert data to yaml and return as string.
		
		Args:
			data: whatever ruamel.yaml accepts
			transform: not super sure to be honest, just gets passed on to ruamel.yaml
		
		'''
		# create temporary "text file"
		tmp = StringIO()

		# dump to tmp
		if self.map_indent != 1 or self.sequence_indent != 1 or self.sequence_dash_offset != 1:
			print('warning: changing indentation may cause this to not work')
		if isinstance(data, JDict):
			data = data._t  # dump underlying dict
		if isinstance(data, UserDict):
			data = data.data  # dump underlying dict
		super().dump(data, tmp, transform=transform)
		tmp.seek(0)

		# convert indentation to tabs and return as string, generated by claude
		return re.sub(r'^ +', lambda m: '\t' * len(m.group(0)), tmp.read(), flags=re.MULTILINE)
		


taml = TAML()
